### ISSUE TITLE
PowerShell installer

### ISSUE THREAD

**Issue by cyclops1982** [K2NE/K2NEServiceBroker#1]
It would be nice to provide a small powershell script to install this project.

**Comment by timmes** [comment]
Just a PowerShell installer script or do we prefer a MSI package?

**Comment by cyclops1982** [comment]
Just a powershell, because then we can also deploy P&D with that and so on...

**Comment by timmes** [comment]
Ok. I've some snippets for this. So you need:
- Copying the ServiceBroker into the right folder (%INSTALLDIR%\k2 blackpearl\ServiceBroker)
- Deploying a P&D package

Anything else?

**Comment by cyclops1982** [comment]
I think we also need:
Registering the ServiceType
Registering the ServiceInstance

**Comment by markman623** [comment]
Hi,
Would this just be a post-build event then?  I'm looking into doing something dirty like this via reflection:

Add-Type -Path $servicesMgmtDllPath;
$serviceMgmtServer = New-Object -TypeName SourceCode.SmartObjects.Services.Management.ServiceManagementServer;
$serviceMgmtServer.RegisterServiceType(parameters...);

I couldn't find anything that was relatively small that already did this, so that is why I didn't reuse something.

I can will work on cleaning this up and adding this if you think it makes sense...

**Comment by cyclops1982** [comment]
@markman623 It would be a separate script. The approach you have is indeed what we're after.
I think some things that are important. Same GUID for the ServiceType and same GUID for the service instance. We should simple 'pick one' for both of them.

**Comment by chevdor** [comment]
See PR #16
It does just that and much more!
I did not write the uninstall script but I left some commented out code. 
This is rather trivial. I did **not** include the automatic registration of the service type because I had some issues with that but this is possible and actually very cool as you can force/ensure which GUID will be used. No more discrepencies.

**Comment by chevdor** [comment]
You might be interested in this gist: https://gist.github.com/chevdor/1e23181e07decff47f7f
